pipeline {
	agent {
		docker {
			image 'composer:latest'
		}
	}
	stages {
		stage('Build') {
			steps {
				sh 'sudo composer install'
			}
		}
		stage('Test') {
			steps {
                sh 'sudo ./vendor/bin/phpunit tests'
            }
		}
	}
}
