pipeline {
	agent {
		docker {
			image 'composer:latest'
		}
	}
	stages {
		stage('Build') {
			steps {
			        sh '''
			            cd jenkins-phpunit-test
			            composer install
			        '''
			}
		}
		stage('Test') {
			steps {
				sh '''
			            cd jenkins-phpunit-test
			            ./vendor/bin/phpunit tests
			        '''
            }
		}
	}
}
